version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/GoatQuery/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/GoatQuery/tests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/GoatQuery.AspNetCore/src"
    schedule:
      interval: "weekly"
