name: Publish dotnet package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Create GoatQuery package
        run: dotnet pack --configuration Release -p:Version=${{ github.event.release.tag_name }} *.csproj
        working-directory: ./src/GoatQuery/src

      - name: Create GoatQuery.AspNetCore package
        run: dotnet pack --configuration Release -p:Version=${{ github.event.release.tag_name }} *.csproj
        working-directory: ./src/GoatQuery.AspNetCore/src

      - name: Publish the GoatQuery package to Nuget
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ./src/GoatQuery/src

      - name: Publish the GoatQuery.AspNetCore package to Nuget
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ./src/GoatQuery.AspNetCore/src
